import express from 'express';
import { login, register } from '../controladores/authController.js';
import { forgotPassword } from '../controladores/forgotPasswordController.js';
import { resetPassword } from '../controladores/resetPasswordController.js';
const router = express.Router();
router.post('/login', login);
router.post('/register', register);
router.post('/forgot-password', forgotPassword);
router.post('/reset-password', resetPassword);
export default router;